# Final Evaluation
## Problem 2.

#### Loading the packages.

In [1]:
from scipy import stats
import numpy as np
import pandas as pd 
import math
import matplotlib.pyplot as plt
from random import seed

In [2]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

#### Making the entries of the logic table.

In [3]:
x_train = np.array([0,1,0,1])                 
y_train = np.array([0,0,1,1])
amp_train = np.array([1,1,1,0])
doll_train = np.array([0,0,0,1])

In [4]:
xy_train = np.append(x_train, y_train).reshape(len(x_train),2, order='F')
xy_train

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

#### Defining the perceptron for the operator &.

In [5]:
def amp_model():
    model = Sequential()
    model.add(Dense(32, activation='relu', input_dim=2))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['binary_accuracy'])
    return model

In [6]:
ampmodel = amp_model()

In [7]:
resultados_amp = ampmodel.fit(xy_train,  amp_train, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.2571 - binary_accuracy: 0.2500
Epoch 2/1000
1/1 [==============================] - 0s 499us/step - loss: 0.2551 - binary_accuracy: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 499us/step - loss: 0.2532 - binary_accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 500us/step - loss: 0.2513 - binary_accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 501us/step - loss: 0.2496 - binary_accuracy: 0.7500
Epoch 6/1000
1/1 [==============================] - 0s 500us/step - loss: 0.2481 - binary_accuracy: 0.7500
Epoch 7/1000
1/1 [==============================] - 0s 500us/step - loss: 0.2468 - binary_accuracy: 0.7500
Epoch 8/1000
1/1 [==============================] - 0s 500us/step - loss: 0.2454 - binary_accuracy: 1.0000
Epoch 9/1000
1/1 [==============================] - 0s 501us/step - loss: 0.2444 - binary_accuracy: 0.7500
Epoch 10/1000
1/1 [====================

#### Defining the percpectron with for opertator $.

In [8]:
def doll_model():
    model = Sequential()
    model.add(Dense(32, activation='relu', input_dim=2))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['binary_accuracy'])
    return model
dollmodel = doll_model()

In [9]:
resultados_doll = dollmodel.fit(xy_train,  doll_train, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 1000us/step - loss: 0.2589 - binary_accuracy: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.2568 - binary_accuracy: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 500us/step - loss: 0.2547 - binary_accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 500us/step - loss: 0.2526 - binary_accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 501us/step - loss: 0.2506 - binary_accuracy: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 499us/step - loss: 0.2486 - binary_accuracy: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 501us/step - loss: 0.2467 - binary_accuracy: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 499us/step - loss: 0.2447 - binary_accuracy: 0.7500
Epoch 9/1000
1/1 [==============================] - 0s 500us/step - loss: 0.2428 - binary_accuracy: 0.7500
Epoch 10/1000
1/1 [===================

#### Now, we test the perceptrons with the following samples.

In [10]:
A = np.array([1.001,0,0.001,1])                 
B = np.array([0,1,0,1])
C = np.array([0,1,1,0])
AampB =  np.append(A, B).reshape(len(A),2, order='F')
AampB

array([[1.001e+00, 0.000e+00],
       [0.000e+00, 1.000e+00],
       [1.000e-03, 0.000e+00],
       [1.000e+00, 1.000e+00]])

#### First, calculate A&B. We can check that the result is correct.

In [11]:
pred_AB = ampmodel.predict(AampB)
print(pred_AB)

[[0.98977816]
 [0.9907675 ]
 [0.9883453 ]
 [0.0110614 ]]


#### Then, calculate (A&B)$C. Again, the result is correct.

In [12]:
ABdollC = np.append(pred_AB, C).reshape(len(pred_AB),2, order='F')
pred_ABC = dollmodel.predict(ABdollC)
print(pred_ABC)

[[0.00366768]
 [0.9923502 ]
 [0.99216723]
 [0.00347912]]
